### ISSUE TITLE
XMLHttpRequest is not defined 

### ISSUE THREAD

**Issue by singhmohancs** [angular/universal-starter#401]
I am using this seed for server side rendering. Everything works perfectly.

Now, Issue occurs when any node_mode make an XMLHttpRequest. I have used https://github.com/backand/angular2-sdk this SDK in an application. This SDK makes an XMLHttpRequest to fetch data from the backend.

Client side rendering does work perfectly because XMLHttpRequest object is available in the browser.

<img width="1229" alt="screen shot 2017-07-12 at 10 15 45 pm" src="https://user-images.githubusercontent.com/283132/28143096-85675406-6781-11e7-8e46-0b1878845c76.png">

**Comment by gdi2290** [comment]
this is a problem of Backand not having a node version
https://github.com/backand/vanilla-sdk/blob/master/src/utils/http.js

**Comment by singhmohancs** [comment]
@gdi2290 

>this is a problem of Backand not having a node version
https://github.com/backand/vanilla-sdk/blob/master/src/utils/http.js

This is not a problem. `universal-starter` does not support `XMLHttpRequest` which is a big issue with this starter. 

I was not able to use following components for Tracking and logging. 

- https://sentry.io/for/angular2/ 
- https://trackjs.com/
- https://analytics.google.com

I did not find any solution to fix this issue. So I moved to PHP now.

**Comment by gdi2290** [comment]
Make sure you `webpack-node-externals` for the server webpack config to avoid this
https://www.npmjs.com/package/webpack-node-externals

**Comment by gdi2290** [comment]
should be fixed via https://github.com/angular/universal-starter/commit/303bb16db6e05c54165812bdbc91de0ac738b7e4

**Comment by mauris** [comment]
`webpack-node-externals` doesn't seem to fix this issue. I still can replicate the error.

**Comment by mauris** [comment]
Looking at https://github.com/alxhub/angular/blob/e73acc6f3023069a1c43605464bad377158bda7c/packages/platform-server/src/http.ts

It seems like we also need to implement our own `XhrFactory` and `BrowserXhr` that creates an instance of xhr2 for XMLHttpRequest on server-side.

**Comment by mauris** [comment]
Upon further investigation, this should have been covered by an import of `ServerModule` from `@angular/platform-server` in the server's app module. :/ I'm still facing the problem

**Comment by ssatz** [comment]
@mauris I am getting error like 
this method getcookie not implemented 

Have you rectified it?

**Comment by abhijeet1403** [comment]
I'm still getting it. Any fixes yet?

**Comment by Vermorxt** [comment]
This issue accours also to me, while I'm using lazy loaded modules and tried to compile application with prerender strategy. 

The solution was for me to remove HttpClientModule from all lazy loaded modules and add it only to app.module.ts.

I hope it helps someone.

**Comment by HolaPI** [comment]
leave something though the problem was long ago.
----------------------------
**Reason:** the XMLHttpRequest is not part of Node.js,  it's only natively supported in browsers. We can use "`npm install xmlhttprequest --save`" and add "`var XMLHttpRequest = require('xmlhttprequest').XMLHttpRequest`"
